version: "3.9"
name: "hearizons"

services:
  # Discord bot
  bot:
    build: bot
    restart: always

    env_file:
      .env

    links:
      - database
    depends_on:
     - database

  # POSTGRESQL database
  database:
    image: postgres:15.0
    restart: always

    env_file:
      .env

    volumes:
      - ./data/postgres:/var/lib/postgresql/data
